name: ybml
channels:
  - conda-forge
  - defaults
dependencies:
  - box2d-py=2.3
  - ffmpeg=6.1
  - graphviz
  - python-graphviz
  - ipython=8.17
  - ipywidgets=8.1
  - joblib=1.3
  - jupyterlab=4.0
  - matplotlib=3.8
  - nbdime=3.2
  - nltk=3.8
  - numexpr=2.8
  - numpy=1.26
  - pandas=2.1
  - pillow=10.1
  - pip
  - py-xgboost=1.7
  - pydot=1.4
  - python=3.10
  - requests=2.31
  - scikit-learn=1.3
  - scipy=1.11
  - statsmodels=0.14
  - tqdm=4.66
  - wheel
  - widgetsnbextension=4.0
  - pip:
    - keras-core
    - keras-tuner~=1.4.6
    - tensorboard-plugin-profile~=2.14.0
    - tensorboard~=2.14.1
    - tensorflow-datasets~=4.9.3
    - tensorflow-hub~=0.15.0
    - tensorflow-serving-api~=2.14.0
    - tensorflow~=2.14.0
    - transformers~=4.35.0
    - urlextract~=1.8.0
    - gymnasium[classic_control,atari,accept-rom-license]
    - google-cloud-aiplatform~=1.36.2
    - google-cloud-storage~=2.13.0